### ISSUE TITLE
What unit is the data in? millivolts or volts?

### ISSUE THREAD

**Issue by ut33** [mark-toma/MyoMex#19]
What unit is the data in? millivolts or volts?

**Comment by mark-toma** [comment]
I'm assuming you're referring to the `MyoData.emg` and `MyoData.emg_log` properties. These are mapped to [-128,127] as int8 data in the Myo SDK from Thalmic Labs. I have scaled them by a factor of 1/128 into the range [-1,0.9921875]. See lines [473](https://github.com/mark-toma/MyoMex/blob/master/MyoMex/MyoData.m#L473) and [243](https://github.com/mark-toma/MyoMex/blob/master/MyoMex/MyoData.m#L243) of [MyoData.m](https://github.com/mark-toma/MyoMex/blob/master/MyoMex/MyoData.m)

They are dimensionless until you calibrate them. I'm not sure what the scale is nor how they're derived from the sEMG sensors in Myo.

Note: accel is in [g], gyro is in [deg/s], quat is quaternions with the scalar component first (i.e. `q = [s,vx,vy,vz]`).
